{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "np.random.seed(4)\n",
    "m = 60\n",
    "w1, w2 = 0.1, 0.3\n",
    "noise = 0.1\n",
    "\n",
    "angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5\n",
    "X = np.empty((m, 3))\n",
    "X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2\n",
    "X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2\n",
    "X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_centered = X - X.mean(axis=0)\n",
    "U, s, Vt = np.linalg.svd(X_centered)\n",
    "c1 = Vt.T[:, 0]\n",
    "c2 = Vt.T[:, 1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "W2 = Vt.T[:,:2]\n",
    "X2D = X_centered.dot(W2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.decomposition import PCA\n",
    "\n",
    "pca = PCA(n_components = 2)\n",
    "X2D = pca.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.84248607, 0.14631839])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pca.explained_variance_ratio_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from six.moves import urllib\n",
    "# from sklearn.datasets import fetch_mldata\n",
    "# mnist = fetch_mldata('MNIST original')\n",
    "from sklearn.datasets import fetch_openml\n",
    "mnist = fetch_openml('mnist_784', version=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X = mnist[\"data\"]\n",
    "y = mnist[\"target\"]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "pca = PCA()\n",
    "pca.fit(X_train)\n",
    "cumsum = np.cumsum(pca.explained_variance_ratio_)\n",
    "d = np.argmax(cumsum >= 0.95) + 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "pca = PCA(n_components = 0.95)\n",
    "X_reduced = pca.fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "pca = PCA(n_components = 154 )\n",
    "X_reduced = pca.fit_transform(X_train)\n",
    "X_recovered = pca.inverse_transform(X_reduced)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "rnd_pca = PCA(n_components = 154, svd_solver = \"randomized\")\n",
    "X_reduced = rnd_pca.fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.decomposition import IncrementalPCA\n",
    "\n",
    "n_batches = 100\n",
    "inc_pca = IncrementalPCA(n_components = 154)\n",
    "for X_batch in np.array_split(X_train, n_batches):\n",
    "    inc_pca.partial_fit(X_batch)\n",
    "\n",
    "X_reduced = inc_pca.transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "filename = \"my_mnist.data\"\n",
    "m, n = X_train.shape\n",
    "\n",
    "X_mm = np.memmap(filename, dtype='float32', mode='write', shape=(m, n))\n",
    "X_mm[:] = X_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "IncrementalPCA(batch_size=525, n_components=154)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_mm = np.memmap(filename, dtype=\"float32\", mode=\"readonly\", shape=(m, n))\n",
    "\n",
    "batch_size = m // n_batches\n",
    "inc_pca = IncrementalPCA(n_components=154, batch_size=batch_size)\n",
    "inc_pca.fit(X_mm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "#from sklearn.decomposition import KernelPCA\n",
    "\n",
    "#rbf_pca = KernelPCA(n_components = 2, kernel = \"rbf\", gamma = 0.04)\n",
    "#X_reduced = rbf_pca.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46666, 46666) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46666, 46666) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46666, 46666) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 280, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 180, in _get_kernel\n",
      "    **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1940, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1360, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 1104, in rbf_kernel\n",
      "    K = euclidean_distances(X, Y, squared=True)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\metrics\\pairwise.py\", line 310, in euclidean_distances\n",
      "    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46666, 46666) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 330, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 296, in _fit\n",
      "    **fit_params_steps[name])\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\pipeline.py\", line 740, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 305, in fit_transform\n",
      "    self.fit(X, **params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 281, in fit\n",
      "    self._fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\decomposition\\_kernel_pca.py\", line 185, in _fit_transform\n",
      "    K = self._centerer.fit_transform(K)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 2069, in transform\n",
      "    K = check_array(K, copy=copy, dtype=FLOAT_DTYPES)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 664, in check_array\n",
      "    array = np.array(array, dtype=dtype, order=order)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.2 GiB for an array with shape (46667, 46667) and data type float64\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "clf = Pipeline([\n",
    "        (\"kpca\", KernelPCA(n_components=2)),\n",
    "        (\"log_reg\", LogisticRegression(solver='liblinear'))\n",
    "    ])\n",
    "\n",
    "param_grid = [{\n",
    "        \"kpca__gamma\": np.linspace(0.03, 0.05, 10),\n",
    "        \"kpca__kernel\": [\"rbf\", \"sigmoid\"]\n",
    "    }]\n",
    "\n",
    "grid_search = GridSearchCV(clf, param_grid, cv=3)\n",
    "grid_search.fit(X, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "rbf_pca = KernelPCA(n_components = 2, kernel = \"rbf\", gamma = 0.0433,\n",
    "                   fit_inverse_transform = True)\n",
    "x_reduced = rbf_pca.fit_transform(X)\n",
    "x_preimage = rbf_pca.inverse_transform(X_reduced)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import mean_squared_error\n",
    "mean_squared_error(X, x_preimage)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
